[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
libloading = { version = "0.8.6" }
communication-data = {path = "./communication-data"}
