#!/usr/bin/env bash

if [[ -z $1 || -z $2 ]]; then
    echo "Usage: rln source_dir target_dir"
    echo "Makes symlink for files from source_dir in target_dir"

    exit 1
fi

for file in $1/*; do
    echo "Making Symlink on file $file"
    ln -sf "$file" $2/
done
