[package]
name = "SirinArcadeReferee"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
libloading = { version = "0.8.6" }
events-bus = {path = "../../sdk/out/rust/events_bus"}
libc = "0.2.170"
walkdir = "2"
